name: ferce_app
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.3
  shared_preferences: ^2.0.13
  firebase_core: ^1.12.0
  firebase_auth: ^3.3.15
  cloud_firestore: ^3.1.9
  cloud_functions: ^3.2.8
  email_auth: ^1.0.0
  flutter_linkify: ^5.0.2
  url_launcher: ^6.1.0
  image_picker: ^0.8.5
  image_picker_for_web: ^2.1.6
  firebase_storage: ^10.2.14
  firebase_storage_web: ^3.2.13
  video_player: ^2.4.0
  video_player_web: ^2.0.8
  flutter_staggered_grid_view: ^0.6.1
  chewie: ^1.3.2
  wakelock_web: ^0.4.0
  flutter_local_notifications: ^9.4.1
  firebase_messaging: ^11.2.15
  flutter_swiper: ^1.1.6
  file_picker: ^4.5.1
  story_view: ^0.13.2
  dio: ^4.0.6
  google_maps_flutter: ^2.1.7
  tflite: ^1.1.2
  flutter_rounded_date_picker: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    #images 
    - assets/images/
    - assets/images/background/
    - assets/vectors/
    - assets/
    - assets/model.tflite
    - assets/labels.txt
    - assets/tf_lite_model.tflite
  fonts:
    - family: Recoleta
      fonts:
        - asset: assets/fonts/Recoleta/Recoleta-Thin.ttf
          style: normal
          weight: 100
        - asset: assets/fonts/Recoleta/Recoleta-Light.ttf
          style: normal
          weight: 300
        - asset: assets/fonts/Recoleta/Recoleta-Regular.ttf
          style: normal
          weight: 400
        - asset: assets/fonts/Recoleta/Recoleta-Medium.ttf
          style: normal
          weight: 500
        - asset: assets/fonts/Recoleta/Recoleta-SemiBold.ttf
          style: normal
          weight: 600
        - asset: assets/fonts/Recoleta/Recoleta-Bold.ttf
          style: normal
          weight: 700
        - asset: assets/fonts/Recoleta/Recoleta-Black.ttf
          style: normal
          weight: 900
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist/Urbanist-Thin.ttf
          style: normal
          weight: 100
        - asset: assets/fonts/Urbanist/Urbanist-ExtraLight.ttf
          style: normal
          weight: 200
        - asset: assets/fonts/Urbanist/Urbanist-Light.ttf
          style: normal
          weight: 300
        - asset: assets/fonts/Urbanist/Urbanist-Regular.ttf
          style: normal
          weight: 400
        - asset: assets/fonts/Urbanist/Urbanist-Medium.ttf
          style: normal
          weight: 500
        - asset: assets/fonts/Urbanist/Urbanist-SemiBold.ttf
          style: normal
          weight: 600
        - asset: assets/fonts/Urbanist/Urbanist-Bold.ttf
          style: normal
          weight: 700
        - asset: assets/fonts/Urbanist/Urbanist-ExtraBold.ttf
          style: normal
          weight: 800
        - asset: assets/fonts/Urbanist/Urbanist-Black.ttf
          style: normal
          weight: 900
   
